name: Build SM64 Windows Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        submodules: 'recursive'
      
    - name: Install Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
      
    - name: Install Android SDK/NDK
      uses: android-actions/setup-android@v2
      with:
        components: 'build-tools;28.0.3,platform-tools,tools'
        ndk-version: '21.0.6113669'
      
    - name: Set up SDL2
      run: |
        curl -LO https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip
        Expand-Archive SDL2-devel-2.0.14-VC.zip -DestinationPath "C:\SDL2"
        echo "::add-path::C:\SDL2\SDL2-2.0.14\lib\x64"
        echo "::add-path::C:\SDL2\SDL2-2.0.14\include"
        
    - name: Install MinGW
      run: |
        choco install mingw
        
    - name: Copy baserom
      run: |
       cp baserom.us.z64 ./app/jni/src/baserom.us.z64
      
    - name: Get SDL sources
      run: ./getSDL.sh
      
    - name: Perform native build
      run: |
        cd app/jni/src
        make --jobs 4
        make --jobs 4
        cd ../../..
      
    - name: Perform Android build
      run: gradlew.bat assembleDebug
