name: Build SM64 Windows Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'

      - uses: msys2/setup-msys2@v2
      
      - name: Fetch Dependencies
        run: pacman -S --noconfirm unzip make git mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-i686-glew mingw-w64-x86_64-glew mingw-w64-i686-SDL2 mingw-w64-i686-SDL mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL python3
        
      - name: Set up Java JDK
        run: |
          mkdir -p "C:\hostedtoolcache\windows\Java_Adopt_jdk\17.0.10-7\x64"
          curl -L https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_windows-x64_bin.zip -o jdk.zip
          tar -xf jdk.zip -C "C:\hostedtoolcache\windows\Java_Adopt_jdk\17.0.10-7\x64"
          rm jdk.zip
          echo "JAVA_HOME=C:\hostedtoolcache\windows\Java_Adopt_jdk\17.0.10-7\x64" >> $GITHUB_ENV

      - name: Set up Android SDK/NDK
        run: |
          mkdir -p "C:\Android\android-sdk"
          curl -L https://dl.google.com/android/repository/commandlinetools-win-7302050_latest.zip -o sdk.zip
          unzip -q sdk.zip -d "C:\Android\android-sdk"
          rm sdk.zip
          echo "ANDROID_HOME=C:\Android\android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=C:\Android\android-sdk" >> $GITHUB_ENV
          
      - name: Run getSDL.sh
        run: ./getSDL.sh

      - name: Make Audio File
        run: |
          make -j $(nproc) -C app/jni/src/tools/audiofile
      
      - name: Copy baserom
        run: |
          cp baserom.us.z64 ./app/jni/src/baserom.us.z64
      
      - name: Perform native build
        run: |
          cd app/jni/src
          make --jobs 4
          make --jobs 4
          cd ../../..
          
      - name: Perform Android build (using cmd.exe)
        shell: cmd
        run: cmd.exe /c "cd D:\a\sm64-port-android-base\sm64-port-android-base && echo 'Executing gradlew.bat' && gradlew.bat assembleDebug && echo 'Gradle build completed'"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: sm64-debug-apk
          path: D:\a\sm64-port-android-base\sm64-port-android-base\app\build\outputs\apk\debug\*.apk
