name: Build SM64 Ubuntu Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'

      - name: Install Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '17'
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Install Android SDK/NDK
        uses: android-actions/setup-android@v3.2.0

      - name: Make Audio File
        run: |
          make -j $(nproc) -C app/jni/src/tools/audiofile
      
      - name: Copy baserom
        run: |
          cp baserom.us.z64 ./app/jni/src/baserom.us.z64
     
      - name: Run getSDL.sh
        run: ./getSDL.sh
        
      - name: Perform native build
        run: |
          cd app/jni/src
          make --jobs 4
          make --jobs 4
          cd ../../..
          
      - name: Gradlew build
        run: |
         ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: sm64-debug-apk
          path: D:\a\sm64-port-android-base\sm64-port-android-base\app\build\outputs\apk\debug\*.apk
