name: Build SM64 Windows Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        submodules: 'recursive'
      
    - name: Install Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
      
    - name: Install Android SDK/NDK
      uses: android-actions/setup-android@v2
      with:
        components: 'build-tools;28.0.3,platform-tools,tools'
        ndk-version: '21.0.6113669'
        
    - name: Install MinGW
      run: |
        choco install mingw
        
    - name: Grant execute permission to getSDL.sh
      run: |
        Get-ChildItem -Path ./ -Recurse -Filter "getSDL.sh" | ForEach-Object { $_.IsReadOnly = $false }
        Get-ChildItem -Path ./ -Recurse -Filter "getSDL.sh" | ForEach-Object { $_.Attributes -= 'ReadOnly' }
      
    - name: Run getSDL.sh
      run: ./getSDL.sh
      
    - name: Copy baserom
      run: |
       cp baserom.us.z64 ./app/jni/src/baserom.us.z64
      
    - name: Perform native build
      run: |
        cd app/jni/src
        make --jobs 4
        make --jobs 4
        cd ../../..
      
    - name: Perform Android build
      run: gradlew.bat assembleDebug
