name: Build SM64 Windows Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        submodules: 'recursive'

    - uses: msys2/setup-msys2@v2
    
    - name: Fetch Dependencies
      run: pacman -S --noconfirm unzip make git mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-i686-glew mingw-w64-x86_64-glew mingw-w64-i686-SDL2 mingw-w64-i686-SDL mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL python3
      
    - name: Install Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
      
    - name: Install Android SDK/NDK
      uses: android-actions/setup-android@v2
      with:
        components: 'build-tools;28.0.3,platform-tools,tools'
        ndk-version: '21.0.6113669'
        
    - name: Run getSDL.sh
      run: ./getSDL.sh

    - name: Make Audio File
      run: |
       make -j $(nproc) -C app/jni/src/tools/audiofile
      
    - name: Copy baserom
      run: |
       cp baserom.us.z64 ./app/jni/src/baserom.us.z64
      
    - name: Perform native build
      run: |
        cd app/jni/src
        make --jobs 4
        make --jobs 4
        cd ../../..

    - name: Perform Android build
      run: gradlew.bat assembleDebug
