name: Build Super Mario 64 Android Port

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone repository with submodules
        run: |
          git clone --recursive https://github.com/VDavid003/sm64-port-android-base --branch sm64ex_nightly
          cd sm64-port-android-base

      - name: Build Docker image
        run: docker build . -t sm64_android

      - name: Copy baserom
        run: cp baserom.us.z64 ./app/jni/src/baserom.us.z64

      - name: Setup symlinks for SDL
        run: |
          docker run --rm -v ${{ github.workspace }}:/sm64 sm64_android sh -c "ln -nsf /SDL2-2.0.12/src /sm64/app/jni/SDL/src"
          docker run --rm -v ${{ github.workspace }}:/sm64 sm64_android sh -c "ln -nsf /SDL2-2.0.12/include /sm64/app/jni/SDL/include"

      - name: List Makefile
        run: ls -al /sm64/app/jni/src

      - name: Perform native build
        run: |
          docker run --rm -v ${{ github.workspace }}:/sm64 sm64_android sh -c "cd /sm64/app/jni/src && make --jobs 4"
          docker run --rm -v ${{ github.workspace }}:/sm64 sm64_android sh -c "cd /sm64/app/jni/src && make --jobs 4"

      - name: Perform Android build
        run: docker run --rm -v ${{ github.workspace }}:/sm64 sm64_android sh -c "./gradlew assembleDebug"

      - name: Display APK file
        run: ls -al ./app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: sm64_android_apk
          path: ./app/build/outputs/apk/debug/app-debug.apk
