name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: 'recursive'
        
    - name: Copy baserom.us.z64
      run: cp baserom.us.z64 ./app/jni/src/baserom.us.z64

    - name: Run getSDL.sh
      run: ./getSDL.sh

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Update submodules
      run: git submodule update --recursive --remote
    
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Make
      run: |
        sudo apt-get update
        sudo apt-get install make

    # Add the NDK download step here
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.4.2
      with:
       ndk-version: r26b    

    - name: Print NDK directory contents
      run: ls -l /usr/local/lib/android/sdk/ndk/
          
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.0
      with:
       cmdline-tools-version: 11076708

    - name: Install necessary dependencies
      run: |
       sudo apt-get update
       sudo apt-get install make libusb-1.0-0-dev libsdl2-dev libgl1-mesa-dev
        
    - name: Compile with Make
      run: |
        cd app/jni/src
        make --jobs 4
        make --jobs 4
        cd ../../..

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.3
      with:
        name: app
        path: ./app/build/outputs/apk/debug/app-debug.apk
